# This is a basic workflow to help you get started with Actions

name: Learning Workflow

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ] 
  pull_request:
    branches: [ "master" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  variable_type: global

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    env:
      variable_type: job

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        env:
          variable_type: step
        run: |
          echo Hello, world!
          echo "Variable type is ${{ env.variable_type }}"
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.

  custom_GITHUB_ENV:
    runs-on: ubuntu-latest
    steps:
    - name: set value
      id: step_one
      run: |
        echo "step_name=set_value" >> $GITHUB_ENV

    - name: show value
      id: step_two
      run: |
        echo "Step value is ${{ env.step_name }}"

